"""
Minimal training demo for ICLR submission.

This script shows how to import the model and run a short training
loop on a dataset. Replace `data_dir` with your dataset path or a
dummy dataset generated by scripts/generate_dummy_data.py.

Usage:
    python examples/minimal_train.py
"""

import torch

# ⚠️ adapte l'import selon ton package final :
# from mrs_yolo.models.mr_yolo import MRSYOLOModel as Model
from ..mrs_yolo.models.mr_yolo import MR_YOLO as Model  # provisoire

def main():
    # Example: single resolution 256x256
    input_resolutions = [(256, 256)]
    device = "cuda:0" if torch.cuda.is_available() else "cpu"

    # Instantiate model
    model = Model(
        num_classes=15,
        device=device,
        reg_max=16,
        output_dir="runs/minimal_demo",
        input_resolutions=input_resolutions,
        width_mult=0.25,
        backbone_mode="pyramid",
        outfusion_channels_mult=1,
    )

    # Train for 1 epoch on dummy or real data
    model.fit(
        data_dir="data_dummy",   # change to your dataset path
        batch_size=2,
        dataset="dataset512",
        epochs=1,
        patience=1,
    )

    print("[done] Minimal demo finished. Check outputs in runs/minimal_demo.")

if __name__ == "__main__":
    main()
